# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.7, 3.8  ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          repo-token: ${{ secrets.AUTH_TOKEN }}

      - name: Setup Mujoco
        run: |
          sudo apt-get update
          sudo apt install -y  libosmesa6-dev  libglew-dev  libgl1-mesa-glx libgl1-mesa-dev libgl1-mesa-glx libglfw3
          sudo apt install -y xpra xserver-xorg-dev patchelf gcc-multilib
          mkdir -p "$HOME/.mujoco"
          cd $HOME/.mujoco
          wget https://github.com/deepmind/mujoco/releases/download/2.1.0/mujoco210-linux-x86_64.tar.gz
          tar -xf mujoco210-linux-x86_64.tar.gz -C "$HOME/.mujoco"
          rm -rf mujoco210-linux-x86_64.tar.gz
      - name: Install dependencies
        run: |
          export MUJOCO_PY_MUJOCO_PATH=$HOME/.mujoco/mujoco210
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.mujoco/mujoco210/bin
          pip3 install --upgrade 'pip<=23.0.1'
          pip3 install --upgrade 'setuptools<=66' 
          pip3 install --upgrade 'wheel<=0.38.4'
          python3 -m pip install flake8
          pip3 install pytest pytest_cases
          pip3 install torch==1.10.2+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
          pip3 install git+https://github.com/koulanurag/opcc@main#egg=opcc
          pip3 install -r requirements.txt
          pip3 freeze
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          export MUJOCO_PY_MUJOCO_PATH=$HOME/.mujoco/mujoco210
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.mujoco/mujoco210/bin
          python -m pytest -v # adds the current directory in the PYTHONPATH and then runs test